# Generated by Django 6.0.5 on 2026-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='◆', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BoardRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Libreville, Gabon', max_length=300)),
                ('phones', models.JSONField(default=list)),
                ('email', models.EmailField(default='lespenseursdugabon@gmail.com', max_length=254)),
                ('status', models.CharField(default='Association à durée illimitée', max_length=200)),
            ],
            options={
                'verbose_name': 'Informations de contact',
            },
        ),
        migrations.CreateModel(
            name='JoinStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('simple', 'Membre Simple'), ('ca', 'Membre du C.A.')], max_length=20)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('period', models.CharField(default='mois', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('benefits', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='◆', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='◆', max_length=10)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Les Penseurs du Gabon', max_length=200)),
                ('acronym', models.CharField(default='L.P.G', max_length=20)),
                ('tagline', models.CharField(default='Pour un Gabon Meilleur', max_length=200)),
                ('description', models.TextField(default="Association citoyenne de réflexion, d'action et d'amélioration du développement du Gabon")),
                ('founded_year', models.IntegerField(default=2024)),
                ('city', models.CharField(default='Libreville', max_length=100)),
                ('country', models.CharField(default='Gabon', max_length=100)),
                ('bureau_members_count', models.IntegerField(default=10)),
                ('objectives_count', models.IntegerField(default=4)),
                ('duration_label', models.CharField(default='∞', max_length=50)),
                ('motto', models.CharField(default='Pour un Gabon Meilleur', max_length=200)),
                ('motto_label', models.CharField(default='LA DEVISE DE L.P.G', max_length=100)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('cta_label', models.CharField(default="ENSEMBLE, BÂTISSONS L'AVENIR 🇬🇦🌍", max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('icon', models.CharField(default='◆', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
