# Generated by Django 6.0.5 on 2026-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_url',
            field=models.ImageField(blank=True, default='', upload_to='static/images/'),
        ),
    ]
